FROM node:20 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build -- --output-path=dist --configuration=prd

FROM nginx:alpine
COPY --from=build /app/dist/browser /usr/share/nginx/html/browser
RUN cp /usr/share/nginx/html/browser/index.csr.html /usr/share/nginx/html/browser/index.html && ls -l /usr/share/nginx/html/browser
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
